%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Benoit Couraud\OneDrive - University of Glasgow\Publications\ISGT_2023\Matlab\AppartmentLoadProfile.xlsx
%    Worksheet: Sheet2
%
% Auto-generated by MATLAB on 19-May-2023 02:10:40

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 6);

% Specify sheet and range
opts.Sheet = "Sheet2";
opts.DataRange = "A2:F4904";

% Specify column names and types
opts.VariableNames = ["Time1", "SmartMeterData", "Time2", "RealTimeData", "Time3", "EV"];
opts.VariableTypes = ["datetime", "double", "datetime", "double", "datetime", "double"];

% Specify variable properties
opts = setvaropts(opts, "Time1", "InputFormat", "");
opts = setvaropts(opts, "Time2", "InputFormat", "");
opts = setvaropts(opts, "Time3", "InputFormat", "");

% Import the data
tbl = readtable("C:\Users\Benoit Couraud\OneDrive - University of Glasgow\Publications\ISGT_2023\Matlab\AppartmentLoadProfile.xlsx", opts, "UseExcel", false);

%% Convert to output type
Time1 = tbl.Time1;
SmartMeterData = tbl.SmartMeterData;
Time2 = tbl.Time2;
RealTimeData = tbl.RealTimeData;
Time3 = tbl.Time3;
EV = tbl.EV;

%% Clear temporary variables
clear opts tbl






       figure5 = figure('Name','Household load example','Color',[1 1 1]);
        % Create axes
        axes1 = axes('Parent',figure5);
        hold(axes1,'on');
%         yyaxis left
        plot1 = plot(Time2,RealTimeData/1000,Time1,SmartMeterData/1000,Time3,EV/1000,'Parent',axes1,'LineWidth',3);
         set(plot1(2),'DisplayName','30 min based smart meter data',...
            'Color','#636363','LineStyle','-','LineWidth',3);      
         set(plot1(1),'DisplayName','Real-Time data',...
            'Color','#71d160','LineStyle','-','LineWidth',2);
         set(plot1(3),'DisplayName','EV charging profile',...
            'Color','#bd700b','LineStyle','-','LineWidth',3);      
         
set(axes1,'ycolor','#000000');
 ylim([-0 9])
  yticks([0 3 6 9])
% datetick('x','mmm dd','keeplimits','keepticks')
        ylabel('Power (kW)');
 
        box(axes1,'on');
        % Set the remaining axes properties
        set(axes1,'FontSize',25,'GridAlpha',0.1,'GridLineStyle',':','LineWidth',1.5,'XGrid','on','YGrid','on');
        % Create legend
        legend(axes1,'show');
        addToolbarExplorationButtons(gcf) % Adds buttons to figure toolbar
        H=gca;
H.LineWidth=1; %change to the desired value 
set(gca, 'FontName', 'Times New Roman')
grid off
% set(legend1,...
%     'Position',[0.554861120765821 0.753682773033207 0.350520823678623 0.17163411631246]);



