%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\Benoit Couraud\OneDrive - University of Glasgow\Publications\ISGT_2023\Matlab\prediction_Seq2Point.csv
%
% Auto-generated by MATLAB on 22-May-2023 22:00:50

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "electricTstove", "washingTmachine", "electricTwaterTheater"];
opts.VariableTypes = ["datetime", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "VarName1", "InputFormat", "yyyy-MM-dd'T'HH:mm:ss");

% Import the data
tbl = readtable("C:\Users\Benoit Couraud\OneDrive - University of Glasgow\Publications\ISGT_2023\Matlab\prediction_Seq2Point.csv", opts);

%% Convert to output type
VarName1 = tbl.VarName1;
electricTstove = tbl.electricTstove;
washingTmachine = tbl.washingTmachine;
electricTwaterTheater = tbl.electricTwaterTheater;

%% Clear temporary variables
clear opts tbl


%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "main"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable("C:\Users\Benoit Couraud\OneDrive - University of Glasgow\Publications\ISGT_2023\Matlab\groundTruth.csv", opts);

%% Convert to output type
VarName11 = tbl.VarName1;
VarName2 = tbl.VarName2;
VarName3 = tbl.VarName3;
VarName4 = tbl.VarName4;
VarName5 = tbl.VarName5;
main = tbl.main;

%% Clear temporary variables
clear opts tbl

d = datetime(VarName11,'ConvertFrom','epochtime','TicksPerSecond',1,'Format',"yyyy-MM-dd'T'HH:mm:ss");



       figure5 = figure('Name','Household load example','Color',[1 1 1]);
        % Create axes
        axes1 = axes('Parent',figure5);
        hold(axes1,'on');
%         yyaxis left
        plot1 = plot(VarName1,electricTstove,VarName1,electricTwaterTheater,d,main,'Parent',axes1,'LineWidth',3);
         set(plot1(2),'DisplayName','30 min based smart meter data',...
            'Color','#636363','LineStyle','-','LineWidth',3);      
         set(plot1(1),'DisplayName','Real-Time data',...
            'Color','#71d160','LineStyle','-','LineWidth',2);
         set(plot1(3),'DisplayName','EV charging profile',...
            'Color','#bd700b','LineStyle','-','LineWidth',3);      
         
set(axes1,'ycolor','#000000');
 ylim([-0 9])
  yticks([0 3 6 9])
% datetick('x','mmm dd','keeplimits','keepticks')
        ylabel('Power (kW)');
 
        box(axes1,'on');
        % Set the remaining axes properties
        set(axes1,'FontSize',25,'GridAlpha',0.1,'GridLineStyle',':','LineWidth',1.5,'XGrid','on','YGrid','on');
        % Create legend
        legend(axes1,'show');
        addToolbarExplorationButtons(gcf) % Adds buttons to figure toolbar
        H=gca;
H.LineWidth=1; %change to the desired value 
set(gca, 'FontName', 'Times New Roman')
grid off
% set(legend1,...
%     'Position',[0.554861120765821 0.753682773033207 0.350520823678623 0.17163411631246]);

